i18n
TheCommonCold/covid-info-service pull request #62
Opened 2021-10-27 11:33 UTC by Vulwsztyn

2021-10-27 11:49 UTC, lukher-dev reviewed
Ogólnie jeszcze ludzie zwykle nazywają te klucz do translacji z _ zamiast camel casem. Np last_update zamiast lastUpdate. Camercasem jeszcze nie widziałem, ale nie będę się upierać, bo to mi obojętne.

2021-10-27 11:49 UTC, lukher-dev commented on src/components/Root.js
> +        <Route path={process.env.PUBLIC_URL + '/:lang'}>
jeżeli skorzystany z i18next-browser-languagedetector to to nie będzie potrzebne

2021-10-27 11:49 UTC, lukher-dev commented on src/components/TopBar.js
> +        <Link className='nav-link' to='/pl'>🇵🇱</Link>
Dzięki i18next-browser-languagedetector język będzie taki sam jak język przeglądarki, jak ktoś będzie chciał sforsować język to wciąż wtedy można paramkiem lang

2021-10-27 11:49 UTC, lukher-dev commented on src/components/statistics/Charts.js
> +import i18n from '../i18n'
Zamiast importować całe i18n to korzystałbym z hooka. Tak polecają https://react.i18next.com/latest/usetranslation-hook

2021-10-30 15:02 UTC, S-Maciejewski requested changes
Nie kumam o co chodzi z a.py, no i te `console.log('fiut')` i inne można wywalić bo lecą do usera

2021-10-30 15:02 UTC, S-Maciejewski commented on scraping/a.py
> +    tab = [pierwsze_slysze_o_przekazywaniu_parametru_przez_referencje for pierwsze_slysze_o_przekazywaniu_parametru_przez_referencje in [listy_trzeba_deep_kopiowac.copy() for listy_trzeba_deep_kopiow
?

2021-10-30 15:02 UTC, S-Maciejewski commented on src/i18n.js
> +console.log('fiut')
ehem, to dalej leci w konsoli :D

2021-10-30 15:04 UTC, S-Maciejewski commented
Imo poza tym co napisałem w review to dobra implementacja i18n, też mi nie przeszkadzają camelCase, w sumie do tej pory tylko z takimi kluczami i18n się spotykałem więc pewnie co firma to konwencja. Nie wiem jak to wygląda w dużych projektach  OSS, bo pewnie one mogą służyć za jakiś wyznacznik, ale imo nie ma się tutaj co przejmować - ważne, że są w jsonach a nie w jakichś szemranych .js/.ts z eksportem

2021-10-31 08:12 UTC, S-Maciejewski approved these changes
u17e

2021-10-31 08:22 UTC, merged